AWSTemplateFormatVersion: '2010-09-09'

Resources:

  CentralEventBusForwardingRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'events.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'AllowSendEventsToCentralBusPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'events:PutEvents'
                Resource: 'REPLACE_WITH_CENTRAL_BUS_ARN'

  AlarmStateChangeEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: 'Listens for CloudWatch Alarm State Change and forwards to central event bus'
      EventPattern:
        source:
          - 'aws.cloudwatch'
        detail-type:
          - 'CloudWatch Alarm State Change'
      State: 'ENABLED'
      Targets:
        - Arn: 'REPLACE_WITH_CENTRAL_BUS_ARN'
          Id: 'Target1'
          RoleArn: !GetAtt [ CentralEventBusForwardingRole, Arn ]

  CrossAccountAugmentationAssumeRole15B0E7B5:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: 'REPLACE_WITH_LAMBDA_ROLE_ARN'
        Version: "2012-10-17"
      Description: Role used by central Alarm event augmentation Lambda function
      RoleName: !Sub "CrossAccountAlarmAugmentationAssumeRole-${AWS::Region}"
    Metadata:
      aws:cdk:path: Application-StacksetComponent-Stack/CrossAccountAugmentationAssumeRole/Resource
      cdk_nag:
        rules_to_suppress:
          - reason: Need query arbitrary alarms
            id: AwsSolutions-IAM5
  CrossAccountAugmentationAssumeRoleDefaultPolicy0B3395D4:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: cloudwatch:ListTagsForResource
            Effect: Allow
            Resource: "*"
          - Action: ec2:DescribeInstances
            Effect: Allow
            Resource: "*"
          - Action:
              - account:GetAlternateContact
              - account:GetContactInformation
            Effect: Allow
            Resource: "*"
          - Action: organizations:DescribeAccount
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: CrossAccountAugmentationAssumeRoleDefaultPolicy0B3395D4
      Roles:
        - Ref: CrossAccountAugmentationAssumeRole15B0E7B5

Outputs:
  CentralEventBusForwardingRoleArn:
    Description: 'ARN of the IAM Role for EventBridge'
    Value: !GetAtt [ CentralEventBusForwardingRole, Arn ]

  AlarmStateChangeEventRuleName:
    Description: 'Name of the EventBridge rule'
    Value: !Ref AlarmStateChangeEventRule
